# Generated by Django 5.2 on 2025-04-11 17:59

import django.core.validators
import storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='volume_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), storage.validators.validate_volume_percentage]),
        ),
    ]
